[package]
name = "slot-gfx"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["host"]
host = ["dep:glutin", "dep:glutin-winit", "dep:winit", "dep:raw-window-handle"]
device = []
test-support = []

[dependencies]
png = { workspace = true }
gl = { workspace = true }
libloading = { workspace = true }
glutin = { workspace = true, optional = true }
glutin-winit = { workspace = true, optional = true }
raw-window-handle = { workspace = true, optional = true }
winit = { workspace = true, optional = true }
