[package]
name = "slot"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["host"]
host = ["dep:winit", "dep:cpal", "dep:gilrs", "slot-gfx/host"]
device = ["slot-gfx/device"]

[dependencies]
zeroize = "1"
slot-labels = { path = "../slot-labels" }
slot-achievements = { path = "../slot-achievements" }
slot-gfx = { path = "../slot-gfx", default-features = false }
slot-input = { path = "../slot-input" }
slot-power = { path = "../slot-power" }
slot-retro = { path = "../slot-retro" }
slot-store = { path = "../slot-store" }
slot-ui = { path = "../slot-ui" }
winit = { workspace = true, optional = true }
cpal = { workspace = true, optional = true }
gilrs = { workspace = true, optional = true }
libc = "0.2"
libloading = { workspace = true }
lz4_flex = { workspace = true }
png = { workspace = true }

[dev-dependencies]
slot-gfx = { path = "../slot-gfx", default-features = false, features = ["test-support"] }
tempfile = { workspace = true }
