use std::collections::BTreeMap;
use std::path::Path;
use std::time::Instant;

use slot::audio::dsp::DspConfig;
use slot::audio::look::{gain_db, LookProcessor, ResamplerKind};
use slot::audio::sinc::{SincQuality, SincResampler};
use slot::audio::AudioLook;

const OWNER: &str = include_str!("../../../card/Audio/ChipTuneEnhance.dsp");
const FIXTURES: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/audio");

fn samples(path: impl AsRef<Path>) -> Vec<f32> {
    std::fs::read(path)
        .unwrap()
        .chunks_exact(4)
        .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
        .collect()
}
fn compare(label: &str, got: &[f32], want: &[f32], tolerance: f32) {
    assert_eq!(got.len(), want.len(), "{label} length");
    let max = got
        .iter()
        .zip(want)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max);
    assert!(got.iter().all(|x| x.is_finite()));
    println!("{label}: max absolute difference {max:.9e}");
    assert!(max < tolerance, "{label}: {max} >= {tolerance}");
}
fn stage(name: &str) -> DspConfig {
    let config = if name == "chain" {
        OWNER.to_owned()
    } else {
        format!(
            "filters = 1\nfilter0 = {name}\n{}",
            OWNER
                .lines()
                .filter(|line| {
                    let line = line.trim();
                    line.starts_with("eq_")
                        || line.starts_with("reverb_")
                        || line.starts_with("iir_")
                        || line.starts_with("panning_")
                })
                .collect::<Vec<_>>()
                .join("\n")
        )
    };
    DspConfig::parse(&config).unwrap()
}
fn check_reference(dir: &Path) {
    let input = samples(dir.join("input.f32le"));
    for name in ["eq", "reverb", "iir", "panning", "chain"] {
        let mut dsp = stage(name).build(32768.0).unwrap();
        let mut got = Vec::new();
        dsp.process(&input, &mut |f| got.extend(f));
        compare(
            name,
            &got,
            &samples(dir.join(format!("{name}.f32le"))),
            1e-4,
        );
    }
    for change in [false, true] {
        let name = if change { "sinc_change" } else { "sinc" };
        let mut r = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
        let mut got = Vec::new();
        let half = input.len() / 2;
        r.process(&input[..half], &mut |f| got.extend(f));
        if change {
            r.set_ratio(1.004);
        }
        r.process(&input[half..], &mut |f| got.extend(f));
        compare(
            name,
            &got,
            &samples(dir.join(format!("{name}.f32le"))),
            1e-4,
        );
    }
}

#[test]
fn reference_golden_equivalence() {
    // Generated by python3 crates/slot/tests/audio_reference.py --golden.
    check_reference(Path::new(FIXTURES));
}

#[test]
#[ignore = "requires python3 crates/slot/tests/audio_reference.py"]
fn reference_live_equivalence() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/audio-reference");
    check_reference(&dir);
    let input = samples(dir.join("input.f32le"));
    for (block, name) in [(2048, "sinc_fast_forward"), (1, "sinc_fast_forward_single")] {
        let mut r = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
        for (part, input) in input.chunks(2048 * 2).enumerate() {
            r.set_ratio(if part == 1 || part == 2 {
                1.0 / 6.0
            } else {
                1.0
            });
            let mut got = Vec::new();
            let warmup = if block == 1 && (part == 1 || part == 3) {
                1800 * 2
            } else {
                0
            };
            r.process(&input[..warmup], &mut |f| got.extend(f));
            for chunk in input[warmup..].chunks(block * 2) {
                r.process(chunk, &mut |f| got.extend(f));
            }
            let want = samples(dir.join(format!("{name}_part{part}.f32le")));
            assert!((got.len() as isize - want.len() as isize).abs() <= 2);
            // C repeats or skips old samples at call boundaries during fades.
            // Compare the unchanged kernels after warmup; Rust's transition
            // pairing is checked against bulk output and continuity below.
            let tail = if part == 0 || part == 2 {
                want.len()
            } else {
                64 * 2
            };
            assert!(got.len() >= tail);
            compare(
                &format!("{name} part {part} settled"),
                &got[got.len() - tail..],
                &want[want.len() - tail..],
                1e-4,
            );
        }
    }
}

#[test]
fn gain_multiplier() {
    assert!((gain_db(-2.0) - 0.7943282347).abs() < 1e-7);
    assert_eq!(gain_db(0.0), 1.0);
}

#[test]
fn block_size_invariance() {
    let input = samples(Path::new(FIXTURES).join("input.f32le"));
    let mut expected_dsp = Vec::new();
    stage("chain")
        .build(32768.0)
        .unwrap()
        .process(&input, &mut |f| expected_dsp.extend(f));
    for quality in [
        SincQuality::Lowest,
        SincQuality::Lower,
        SincQuality::Normal,
        SincQuality::Higher,
        SincQuality::Highest,
    ] {
        let mut expected_sinc = Vec::new();
        SincResampler::new(32768.0, 48000.0, quality)
            .process(&input, &mut |f| expected_sinc.extend(f));
        for size in [1, 7, 512, input.len() / 2] {
            let mut dsp = stage("chain").build(32768.0).unwrap();
            let mut sinc = SincResampler::new(32768.0, 48000.0, quality);
            let (mut got_dsp, mut got_sinc) = (Vec::new(), Vec::new());
            for block in input.chunks(size * 2) {
                dsp.process(block, &mut |f| got_dsp.extend(f));
                sinc.process(block, &mut |f| got_sinc.extend(f));
            }
            compare("DSP block invariance", &got_dsp, &expected_dsp, 1e-6);
            compare("sinc block invariance", &got_sinc, &expected_sinc, 1e-6);
        }
    }
}

#[test]
fn sinc_ratio_change_preserves_stream_state_across_blocks() {
    let input = samples(Path::new(FIXTURES).join("input.f32le"));
    let render = |block: usize| {
        let mut r = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
        let mut out = Vec::new();
        for (half, input) in input.chunks(input.len() / 2).enumerate() {
            r.set_ratio(if half == 0 { 1.0 } else { 1.004 });
            for chunk in input.chunks(block * 2) {
                r.process(chunk, &mut |f| out.extend(f));
            }
        }
        out
    };
    let expected = render(input.len() / 2);
    for block in [1, 7, 512] {
        compare("ratio change", &render(block), &expected, 1e-6);
    }
}

#[test]
fn fast_forward_crossfade_is_independent_of_call_size() {
    let input = samples(Path::new(FIXTURES).join("input.f32le"));
    let render = |quality: SincQuality, block: usize| {
        let mut r = SincResampler::new(32768.0, 48000.0, quality);
        let mut out = Vec::new();
        for (part, input) in input.chunks(1024 * 2).cycle().take(12).enumerate() {
            r.set_ratio(if (3..9).contains(&part) {
                1.0 / 6.0
            } else {
                1.0
            });
            for chunk in input.chunks(block * 2) {
                r.process(chunk, &mut |f| out.extend(f));
            }
        }
        out
    };
    for quality in [
        SincQuality::Lowest,
        SincQuality::Lower,
        SincQuality::Normal,
        SincQuality::Higher,
        SincQuality::Highest,
    ] {
        let bulk = render(quality, 1024);
        for block in [1, 7, 64] {
            // Equal stream positions should have only floating-point rounding error,
            // not a sample of phase error or an unblended cold-path discontinuity.
            compare(
                &format!("fast-forward {quality:?} {block}-frame calls"),
                &render(quality, block),
                &bulk,
                1e-6,
            );
        }
    }
}

#[test]
fn fast_forward_crossfade_keeps_a_constant_signal_continuous() {
    let mut r = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
    let mut out = Vec::new();
    r.process(&vec![0.2; 4096 * 2], &mut |f| out.push(f[0]));
    out.clear();
    for ratio in [1.0 / 6.0, 1.0] {
        r.set_ratio(ratio);
        for _ in 0..4096 {
            r.process(&[0.2; 2], &mut |f| out.push(f[0]));
        }
    }
    let jump = out
        .windows(2)
        .map(|s| (s[1] - s[0]).abs())
        .fold(0.0f32, f32::max);
    println!("DC fast-forward maximum adjacent jump: {jump:.9e}");
    assert!(jump < 1e-3, "DC discontinuity: {jump}");
    assert!(out.iter().all(|&s| (s - 0.2).abs() < 1e-3));
}

#[test]
fn interrupted_fast_forward_crossfade_keeps_dc_continuous() {
    for (rate, quality, fast_frames) in [
        (8000.0, SincQuality::Highest, 3294),
        (48000.0, SincQuality::Higher, 129),
    ] {
        for block in [1, 7, 64, 20000] {
            let mut r = SincResampler::new(32768.0, rate, quality);
            let input = vec![0.2; 20000 * 2];
            r.process(&input, &mut |_| {});
            let mut out = Vec::new();
            for (ratio, frames) in [(1.0 / 6.0, fast_frames), (1.0, 20000)] {
                r.set_ratio(ratio);
                for chunk in input[..frames * 2].chunks(block * 2) {
                    r.process(chunk, &mut |f| out.extend(f));
                }
            }
            let deviation = out.iter().map(|&s| (s - 0.2).abs()).fold(0.0, f32::max);
            println!("{rate} Hz {quality:?} {block}-frame calls: DC deviation {deviation:.9e}");
            assert!(
                deviation < 1e-3,
                "{rate} Hz {quality:?} {block}-frame calls: DC deviation {deviation}"
            );
        }
    }
}

#[test]
fn interrupted_fast_forward_crossfades_are_identical_across_call_sizes() {
    let source = samples(Path::new(FIXTURES).join("input.f32le"));
    let input: Vec<f32> = source.iter().copied().cycle().take(40000 * 2).collect();
    let render = |rate, quality, block: usize| {
        let mut r = SincResampler::new(32768.0, rate, quality);
        let mut out = Vec::new();
        for (ratio, frames) in [
            (1.0, 8192),
            (1.0 / 6.0, 17),
            (1.0, 40000),
            (1.0 / 6.0, 40000),
            (1.0, 17),
            (1.0 / 6.0, 40000),
            (1.0, 40000),
        ] {
            r.set_ratio(ratio);
            for chunk in input[..frames * 2].chunks(block * 2) {
                r.process(chunk, &mut |f| out.extend(f));
            }
        }
        out
    };
    for rate in [8000.0, 48000.0] {
        for quality in [
            SincQuality::Lowest,
            SincQuality::Lower,
            SincQuality::Normal,
            SincQuality::Higher,
            SincQuality::Highest,
        ] {
            let bulk = render(rate, quality, 40000);
            for block in [1, 7, 64] {
                let got = render(rate, quality, block);
                assert_eq!(
                    got.len(),
                    bulk.len(),
                    "{rate} Hz {quality:?} {block}-frame calls: length"
                );
                assert!(
                    got == bulk,
                    "{rate} Hz {quality:?} {block}-frame calls: first mismatch {:?}",
                    got.iter().zip(&bulk).position(|(a, b)| a != b)
                );
            }
        }
    }
}

#[test]
fn fast_forward_rejects_content_above_output_nyquist() {
    let rms = |hz: f64| {
        let mut r = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
        r.set_ratio(1.0 / 6.0);
        let input: Vec<f32> = (0..16384)
            .flat_map(|i| {
                let value = (std::f64::consts::TAU * hz * i as f64 / 32768.0).sin() as f32;
                [value, value]
            })
            .collect();
        let mut out = Vec::new();
        r.process(&input, &mut |f| out.push(f[0]));
        let settled = &out[2048..];
        (settled.iter().map(|&x| x as f64 * x as f64).sum::<f64>() / settled.len() as f64).sqrt()
    };
    assert!(rms(1000.0) > 0.65);
    assert!(rms(8000.0) < 1e-4);
}

fn owner_entries() -> BTreeMap<String, String> {
    [
        ("slot_audio_rate", "48000"),
        ("slot_audio_latency_ms", "256"),
        ("slot_audio_resampler", "sinc"),
        ("slot_audio_resampler_quality", "HIGHER"),
        ("slot_audio_sync", "true"),
        ("slot_audio_gain_db", "-2.0"),
        ("slot_audio_dsp", "ChipTuneEnhance.dsp"),
    ]
    .into_iter()
    .map(|(k, v)| (k.to_owned(), v.to_owned()))
    .collect()
}
#[test]
fn full_owner_look_and_empty_map() {
    let base = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../card/Audio");
    let look = AudioLook::from_entries(&owner_entries(), &base, base.parent().unwrap()).unwrap();
    assert_eq!(look.rate, Some(48000));
    assert_eq!(look.latency_ms, Some(256));
    assert_eq!(look.resampler, Some(ResamplerKind::Sinc));
    assert_eq!(look.quality, Some(SincQuality::Higher));
    assert_eq!(look.sync, Some(true));
    assert_eq!(look.gain_db, Some(-2.0));
    assert!(look.dsp.is_some());
    let empty = AudioLook::from_entries(&BTreeMap::new(), &base, base.parent().unwrap()).unwrap();
    assert_eq!(empty, AudioLook::default());
    assert_eq!(empty.output_rate(), 32768);
    assert_eq!(empty.output_latency_ms(), 40);
    assert_eq!(empty.gain(), 1.0);
    let unrelated = BTreeMap::from([("shader0".into(), "unrelated".into())]);
    assert_eq!(
        AudioLook::from_entries(&unrelated, &base, base.parent().unwrap()).unwrap(),
        empty
    );
}
#[test]
fn invalid_look_entries_are_explicit_errors() {
    for (key, values) in [
        ("slot_audio_rate", vec!["0", "-1", "banana", "4294967296"]),
        (
            "slot_audio_latency_ms",
            vec!["0", "-1", "banana", "4294967296"],
        ),
        ("slot_audio_resampler", vec!["nearest", "SINC", ""]),
        ("slot_audio_resampler_quality", vec!["ultra", ""]),
        ("slot_audio_sync", vec!["false", "TRUE", "0"]),
        (
            "slot_audio_gain_db",
            vec!["NaN", "inf", "-inf", "banana", "1000"],
        ),
        ("slot_audio_dsp", vec!["does-not-exist.dsp", ""]),
    ] {
        for value in values {
            let map = BTreeMap::from([(key.to_owned(), value.to_owned())]);
            let error = AudioLook::from_entries(&map, Path::new(FIXTURES), Path::new(FIXTURES))
                .unwrap_err();
            assert!(error.to_string().contains(key), "{key}: {error}");
        }
    }
}
#[test]
fn dsp_paths_stay_inside_card() {
    let temp = tempfile::tempdir().unwrap();
    let card = temp.path().join("card");
    let base = card.join("Shaders/handheld");
    std::fs::create_dir_all(&base).unwrap();
    std::fs::create_dir_all(card.join("Audio")).unwrap();
    let valid = card.join("Audio/ChipTuneEnhance.dsp");
    let outside = temp.path().join("outside.dsp");
    std::fs::write(&valid, OWNER).unwrap();
    std::fs::write(&outside, OWNER).unwrap();
    let parse = |path: &str| {
        AudioLook::from_entries(
            &BTreeMap::from([("slot_audio_dsp".into(), path.into())]),
            &base,
            &card,
        )
    };
    assert!(parse("../../Audio/ChipTuneEnhance.dsp")
        .unwrap()
        .dsp
        .is_some());
    assert!(parse(valid.to_str().unwrap())
        .unwrap_err()
        .to_string()
        .contains("absolute"));
    assert!(parse("../../../outside.dsp")
        .unwrap_err()
        .to_string()
        .contains("escapes"));
    #[cfg(unix)]
    {
        std::os::unix::fs::symlink(&outside, base.join("escape.dsp")).unwrap();
        assert!(parse("escape.dsp")
            .unwrap_err()
            .to_string()
            .contains("escapes"));
        std::os::unix::fs::symlink(&valid, base.join("inside.dsp")).unwrap();
        assert!(parse("inside.dsp").unwrap().dsp.is_some());
    }
}

#[test]
fn dsp_defaults_and_rejected_filters() {
    for name in ["eq", "reverb", "iir", "panning"] {
        let mut dsp = DspConfig::parse(&format!("filters=1\nfilter0={name}"))
            .unwrap()
            .build(32768.0)
            .unwrap();
        let mut output = Vec::new();
        dsp.process(&[0.0; 1024], &mut |f| output.extend(f));
        assert!(output.iter().all(|&x| x == 0.0));
    }
    for config in [
        "filters=1\nfilter0=chorus",
        "filters=1\nfilter0=iir\niir_type=oops",
        "filters=1\nfilter0=eq\neq_gains=NaN",
        "filters=-1",
        "filters=1",
        "bad line",
        "filters=1\nfilter0=reverb\nreverb_drytime=banana",
    ] {
        assert!(DspConfig::parse(config).is_err(), "{config}");
    }
    assert!(
        DspConfig::parse("filters=1\nfilter0=iir\niir_type=RIAA_phono")
            .unwrap()
            .build(32768.0)
            .is_err()
    );
}

#[test]
fn float_path_clips_only_after_dsp_and_user_volume_is_separate() {
    let look=AudioLook { dsp:Some(DspConfig::parse("filters=2\nfilter0=panning\nfilter1=panning\nfilter0_left_mix=\"4 0\"\nfilter0_right_mix=\"0 4\"\nfilter1_left_mix=\"0.25 0\"\nfilter1_right_mix=\"0 0.25\"").unwrap()),..AudioLook::default() };
    let mut p = LookProcessor::new(&look, 32768.0, 32768.0, 32768).unwrap();
    let mut got: Vec<i16> = Vec::new();
    p.process(&[20000, -20000, 20000, -20000], 1.0, 0.5, &mut |s| {
        got.extend(s)
    });
    assert_eq!(got, [0, 0, 10000, -10000]);
}

#[test]
#[ignore = "host throughput benchmark; run with --release --ignored --nocapture"]
fn benchmark_ten_seconds() {
    let look = AudioLook {
        rate: Some(48000),
        gain_db: Some(-2.0),
        resampler: Some(ResamplerKind::Sinc),
        quality: Some(SincQuality::Higher),
        dsp: Some(stage("chain")),
        ..AudioLook::default()
    };
    let source = samples(Path::new(FIXTURES).join("input.f32le"));
    let input: Vec<i16> = (0..32768 * 10 * 2)
        .map(|i| (source[i % source.len()] * 32768.0) as i16)
        .collect();
    for ratio in [1.0, 1.0 / 6.0] {
        let mut pipeline = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
        let start = Instant::now();
        let mut count = 0;
        let mut checksum = 0i64;
        for block in input.chunks(512 * 2) {
            pipeline.process(block, ratio, 1.0, &mut |out| {
                count += out.len() / 2;
                checksum += out.iter().map(|&x| x as i64).sum::<i64>();
                std::hint::black_box(out);
            });
        }
        println!("10 seconds gain + ChipTuneEnhance + sinc HIGHER ratio {ratio:.9}: {:.6} host seconds, {count} output frames, checksum {checksum}; H700 CPU cost unmeasured",start.elapsed().as_secs_f64());
        assert!((479000.0 * ratio..481000.0 * ratio).contains(&(count as f64)));
    }
}

struct AllocationCounter;
std::thread_local! {
    static ALLOCATIONS: std::cell::Cell<Option<usize>> = const { std::cell::Cell::new(None) };
}
unsafe impl std::alloc::GlobalAlloc for AllocationCounter {
    unsafe fn alloc(&self, layout: std::alloc::Layout) -> *mut u8 {
        let _ = ALLOCATIONS.try_with(|counter| {
            if let Some(count) = counter.get() {
                counter.set(Some(count + 1));
            }
        });
        unsafe { std::alloc::System.alloc(layout) }
    }
    unsafe fn dealloc(&self, pointer: *mut u8, layout: std::alloc::Layout) {
        unsafe { std::alloc::System.dealloc(pointer, layout) }
    }
    unsafe fn realloc(&self, pointer: *mut u8, layout: std::alloc::Layout, size: usize) -> *mut u8 {
        let _ = ALLOCATIONS.try_with(|counter| {
            if let Some(count) = counter.get() {
                counter.set(Some(count + 1));
            }
        });
        unsafe { std::alloc::System.realloc(pointer, layout, size) }
    }
}
#[global_allocator]
static ALLOCATOR: AllocationCounter = AllocationCounter;

#[test]
fn look_processing_does_not_allocate() {
    let look = AudioLook {
        resampler: Some(ResamplerKind::Sinc),
        quality: Some(SincQuality::Higher),
        dsp: Some(stage("chain")),
        gain_db: Some(-2.0),
        ..AudioLook::default()
    };
    let mut p = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
    let mut count = 0;
    ALLOCATIONS.with(|c| c.set(Some(0)));
    for ratio in [1.004, 1.0 / 6.0, 1.0, 1.0 / 6.0, 1.004] {
        for _ in 0..16 {
            p.process(&[1200; 1024], ratio, 0.81, &mut |out| {
                count += out.len();
                std::hint::black_box(out);
            });
        }
    }
    let allocations = ALLOCATIONS.with(|c| c.replace(None).unwrap());
    assert_eq!(allocations, 0);
    assert!(count > 20000);
}

#[test]
fn pipeline_block_size_invariance() {
    let look = AudioLook {
        resampler: Some(ResamplerKind::Sinc),
        quality: Some(SincQuality::Higher),
        dsp: Some(stage("chain")),
        gain_db: Some(-2.0),
        ..AudioLook::default()
    };
    let input: Vec<i16> = samples(Path::new(FIXTURES).join("input.f32le"))
        .iter()
        .map(|x| (x * 32768.0).round() as i16)
        .collect();
    let render = |size: usize| {
        let mut p = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
        let mut out = Vec::new();
        for block in input.chunks(size * 2) {
            p.process(block, 1.004, 0.81, &mut |s| out.extend_from_slice(s));
        }
        out
    };
    let expected = render(input.len() / 2);
    for size in [1, 7, 512] {
        assert_eq!(render(size), expected);
    }
}

fn owner_look() -> AudioLook {
    let base = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../card/Audio");
    AudioLook::from_entries(&owner_entries(), &base, base.parent().unwrap()).unwrap()
}

fn owner_input(frames: usize) -> Vec<i16> {
    let source = samples(Path::new(FIXTURES).join("input.f32le"));
    source
        .iter()
        .cycle()
        .take(frames * 2)
        .map(|x| (x * 32768.0).round() as i16)
        .collect()
}

#[test]
fn video_batches_match_bulk_dsp_then_sinc_across_fast_forward() {
    let look = owner_look();
    let input = owner_input(549 * 20);
    let mut pipeline = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
    let mut dsp = look.dsp.as_ref().unwrap().build(32768.0).unwrap();
    let mut sinc = SincResampler::new(32768.0, 48000.0, SincQuality::Higher);
    let gain = look.gain() / 32768.0;
    let mut got = Vec::new();
    let mut want = Vec::new();
    for ratio in [1.0, 1.0 / 6.0, 1.0] {
        let floats: Vec<f32> = input.iter().map(|&x| x as f32 * gain).collect();
        let mut processed = Vec::new();
        dsp.process(&floats, &mut |f| processed.extend(f));
        sinc.set_ratio(ratio);
        sinc.process(&processed, &mut |f| {
            want.extend(f.map(|s| (s * 32768.0).round() as i16))
        });
        for video in input.chunks(549 * 2) {
            pipeline.process(video, ratio, 1.0, &mut |s| got.extend_from_slice(s));
        }
    }
    assert_eq!(got, want);
}

#[test]
fn mute_and_half_volume_apply_to_owner_dsp_tails() {
    for kind in [ResamplerKind::Linear, ResamplerKind::Sinc] {
        let mut look = owner_look();
        look.resampler = Some(kind);
        let mut full = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
        let mut half = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
        let mut muted = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
        let input = owner_input(4096);
        for p in [&mut full, &mut half, &mut muted] {
            p.process(&input, 1.0, 1.0, &mut |_| {});
        }
        let (mut a, mut b, mut c) = (Vec::new(), Vec::new(), Vec::new());
        for _ in 0..12 {
            full.process(&[0; 549 * 2], 1.0, 1.0, &mut |s| a.extend_from_slice(s));
            half.process(&[0; 549 * 2], 1.0, 0.5, &mut |s| b.extend_from_slice(s));
            muted.process(&[0; 549 * 2], 1.0, 0.0, &mut |s| c.extend_from_slice(s));
        }
        assert_eq!(a.len(), b.len());
        assert_eq!(a.len(), c.len());
        assert!(
            a.iter().filter(|&&s| s != 0).count() > 1000,
            "unprimed {kind:?} tails"
        );
        assert!(c.iter().all(|&s| s == 0), "mute leaked {kind:?} tails");
        assert!(
            a.iter()
                .zip(&b)
                .all(|(&a, &b)| (a as f32 * 0.5 - b as f32).abs() <= 1.0),
            "half-volume {kind:?} tails"
        );
    }
}

#[test]
fn large_eq_bursts_use_bounded_scratch_without_allocating() {
    let look = AudioLook {
        resampler: Some(ResamplerKind::Sinc),
        dsp: Some(DspConfig::parse("filters=1\nfilter0=eq\neq_block_size_log2=12").unwrap()),
        ..AudioLook::default()
    };
    let input = owner_input(8192);
    let floats: Vec<f32> = input.iter().map(|&s| s as f32 / 32768.0).collect();
    let mut processed = Vec::new();
    look.dsp
        .as_ref()
        .unwrap()
        .build(32768.0)
        .unwrap()
        .process(&floats, &mut |f| processed.extend(f));
    let mut want = Vec::new();
    SincResampler::new(32768.0, 48000.0, SincQuality::Normal).process(&processed, &mut |f| {
        want.extend(f.map(|s| (s * 32768.0).round() as i16))
    });
    let mut got = Vec::with_capacity(want.len());
    let mut p = LookProcessor::new(&look, 32768.0, 32768.0, 48000).unwrap();
    ALLOCATIONS.with(|c| c.set(Some(0)));
    p.process(&input, 1.0, 1.0, &mut |s| got.extend_from_slice(s));
    let allocations = ALLOCATIONS.with(|c| c.replace(None).unwrap());
    assert_eq!(allocations, 0);
    assert_eq!(got, want);
}
