[package]
name = "slot-ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zeroize = "1"
fontdue = { workspace = true }
png = { workspace = true }
resvg = { workspace = true }
usvg = { workspace = true }
slot-gfx = { path = "../slot-gfx", default-features = false }
slot-power = { path = "../slot-power" }
slot-store = { path = "../slot-store" }

[dev-dependencies]
slot-gfx = { path = "../slot-gfx", features = ["test-support"] }
tempfile.workspace = true
